# Generated by Django 5.0.6 on 2024-05-27 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_carrito_itemcarrito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
